name: canucks_pricing

channels:
  - defaults
  - conda-forge
  - python
  - pytorch

dependencies:
  - python
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.4.2
  - plotly=5.22.0
  - altair=5.3.0
  - myst-nb=1.1.0
  - pyarrow=16.1.0
  - fastparquet=2024.2.0
  - vegafusion-python-embed=1.6.9
  - vegafusion=1.6.9
  - joblib=1.4.2
  - pytorch=2.3.0
  - xgboost=2.0.3
  - dash=2.11.1
  - dash-bootstrap-components=1.4.1
  - seaborn=0.13.0
  - pip
  - pip:
    - kaleido
    - pyppeteer
    - vl-convert-python>=1.3.0
    - pytorch-tabnet==4.1.0

